/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.sirnoob97.jdup;

import com.github.sirnoob97.jdup.cli.InvalidInputHandler;
import com.github.sirnoob97.jdup.cli.JDupOption;
import picocli.CommandLine;

public class App {

  public static void main(String[] args) {
    var options = new JDupOption();
    var code = new CommandLine(options)
        .setParameterExceptionHandler(new InvalidInputHandler())
        .execute(args);

    System.exit(code);
  }
}
